name: build
run-name: build-lib
on: workflow_call

env:
      name: builder
      BUILD_DIR: build

jobs:
  build_lib:
    runs-on: ubuntu-latest      
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: python setup.py build -b ${{ env.BUILD_DIR }}
